### ISSUE TITLE
SVG export

### ISSUE THREAD

**Issue by nowthis** [nowthis/sankeymatic#1]
Add a function similar to the PNG export where the user can copy (or save to a file) the SVG version of the graph.

Obviously we need to retain nodes, flows, and their colors.

Further features to include in the SVG for which it would be nice to give the user control over their inclusion:
- The **Tooltips** on flows & on nodes
- **Change in opacity** when hovering over the flows
- **Draggability** of nodes, including the subsequent re-rendering of the flows
  - Also: Control over vertical-only draggability vs. vertical+horizontal

**Comment by teleksterling** [comment]
As a workaround - I did manage to simply view the page code, and copiy out the 'the_svg' object to a text file and import into inkscape.

Of course there is no interactivity in this version as suggested above.

**Comment by nowthis** [comment]
Added an easy way for a user to copy the SVG code with tooltips preserved.

The "Further features" listed in the original comment above may not be needed by anyone, so I will refrain from filing a followup issue for those until I hear otherwise.
