### ISSUE TITLE
IMPROVEMENT IDEA: Export with transparent background

### ISSUE THREAD

**Issue by m43stro** [nowthis/sankeymatic#31]
Hi Steve,
great job! I really appreciate this project.
Sometimes I embed the flow diagrams in presentations with non-white background.
It would be nice to have an export option with transparent background for PNG.

Idea:
add transparent check box in "Colors:" > "Background Color:" section

Thanks
Eugen

**Comment by nowthis** [comment]
Working on this feature now. I plan to ship it in the next week.

**Comment by m43stro** [comment]
Great news Steve!
Looking forward to test it.
Thank you very much and a happy new year!

**Comment by stefanpawlik** [comment]
Hi, is the feature implemented yet? Looking forward to using it!

**Comment by nowthis** [comment]
Apologies, folks, life was busier than I anticipated.
I've got the change coded, it works in FF/Chrome/Safari, and I hope to check it in & promote it this week.

**Comment by nowthis** [comment]
Feature is coded, pushed, & live as of this morning:
http://sankeymatic.com/build/

**Comment by m43stro** [comment]
awesome! works great
