### ISSUE TITLE
Node labels can be confusing

### ISSUE THREAD

**Issue by DavidAyliffe** [nowthis/sankeymatic#40]
Node labels seem to be left aligned when nodes are left of centre in the diagram and right aligned when the notes are right of centre.

This causes some problems with understanding the nodes.

Can they be always at the left/right or maybe make this configurable.

Thanks

![sankeymatic_1200x1200 2](https://user-images.githubusercontent.com/28589036/40350776-680c47c6-5db3-11e8-8b82-88adc658a47d.png)

**Comment by Mitalee** [comment]
same problem here - in my case, it seems to occur the moment i put in a third level
![image](https://user-images.githubusercontent.com/5144837/53817393-57f21e00-3f8b-11e9-93eb-44bf7c595737.png)

Is there a way to configure this?

**Comment by nowthis** [comment]
Good news folks, there's a feature just added to the website which lets you set the **Position** for Labels to be all-on-the-left or all-on-the-right (or keep the current automatic-placement behavior).

One wrinkle is that currently you'll have to _manually_ change your left or right **Margin** to make sufficient room for the relocated Labels to fully appear in the diagram's canvas. Auto-adjusting the layout is a feature for another day.

I'll be pushing the code up here someday soon, but the feature is live now at http://sankeymatic.com/build/
