### ISSUE TITLE
Add missing JS files in "build" directory

### ISSUE THREAD

**Issue by interference-security** [nowthis/sankeymatic#44]
The below-mentioned files are missing in the "build" directory, due to which the offline use of this application does not work. It requires manually downloading and adding files inside "build" directory.
1. [d3.v2.js](http://sankeymatic.com/build/d3.v2.js)
2. [sankey.js](http://sankeymatic.com/build/sankey.js)
3. [canvg.js](http://sankeymatic.com/build/canvg.js)
4. [rgbcolor.js](http://sankeymatic.com/build/rgbcolor.js)

**Comment by TappaNuKegga** [comment]
Thanks for the tip.  I manually added these files to my build directory, but I still have a dumb question to ask: How does one get this Sankey site to work?  Whenever I open the index.html in Chrome/Edge, I can't seem to get a diagram to be generated.  Any button I try to click just resets all my inputted values back to default homepage.  What am I doing wrong?  Many thanks!

**Comment by nowthis** [comment]
As of de75709 (posted today), it should be possible to run this locally on a machine more easily - d3 and canvg do not have to be installed separately any more.

@TappaNuKegga - there are some inputs which can trigger a crash (which can cause a reset of the UI). If the latest version (or the live site itself) is still giving you an error, feel free to send me the inputs you're using and I'll see what is causing the reset.
