### ISSUE TITLE
Website could be HTTPS to reassure users & speed up access

### ISSUE THREAD

**Issue by unquietwiki** [nowthis/sankeymatic#46]
At this point (Early 2020), a number of web servers support [HTTP/2](https://en.wikipedia.org/wiki/HTTP/2) out-of-the box, and that can be paired with [Let's Encrypt](https://letsencrypt.org/). [Caddy](https://caddyserver.com/) does both, out-of-box.

**Comment by nowthis** [comment]
https://sankeymatic.com/ is now live via Let's Encrypt. Thanks for the suggestion.

**Comment by unquietwiki** [comment]
Thanks @nowthis !!!!
