### ISSUE TITLE
Sequence of Nodes

### ISSUE THREAD

**Issue by Sharmeela16** [nowthis/sankeymatic#47]
Sankey diagram is showing the sequence of nodes randomly. Is it possible to show the nodes in the ascending order of data entered, so that it displays passenger boarding from a stop and alighting at a stop using bus form first stop to last stop sequentially?

**Comment by nowthis** [comment]
There's now an option immediately under the Input field to force the diagram to use the specific order of the input data.

Look for "Arrange the diagram" and choose "Using the exact input order".
