### ISSUE TITLE
Ordering of Nodes?

### ISSUE THREAD

**Issue by rwat1** [nowthis/sankeymatic#51]
Is there a way to specify the Order of the Nodes?

Is there a logic behind it? (alphanumeric of node label, frequency ascending, or random)?

I would like to specify an order to put some nodes at the bottom area and re-arrange it.

NINJA EDIT:  I just learned about dragging and ordering via 'click-and-drag', but my problem then is the re-ordering doesn't occur, so it kinda just overlays or floats in front of other nodes.

**Comment by jtagcat** [comment]
The ordering is inherited from the input. Reorder the input, and see the change.

**Comment by nowthis** [comment]
There's now an option immediately under the Input field to force the diagram to use the specific order of the input data. Look for "Arrange the diagram" and choose "Using the exact input order".
