### ISSUE TITLE
weird ordering

### ISSUE THREAD

**Issue by totti4ever** [nowthis/sankeymatic#52]
![grafik](https://user-images.githubusercontent.com/49901208/153753098-4f54ace7-3aff-49b4-b0be-6fd9fef4f7e2.png)

What I don't understand:

1. Why isn't Amount8 above Amount25?
2. Why isn't Amount29 above Amount16?
3. Why isn't Amount23 above Amount18?

Great tool, by the way!!

```
Amount6 [27165] Amount4
Amount2 [810] Amount4
Amount3 [1410] Amount4

Amount4 [6435] Amount11
Amount11 [6053] Amount9
Amount11 [0] Amount10
Amount11 [383] Amount7

Amount4 [22950] Amount5
Amount5 [1800] Amount8
Amount5 [21150] Amount25

Amount29 [3285] Amount25

Amount17 [38528] Amount15
Amount15 [16080] Amount22

Amount22 [2865] Amount18
Amount22 [3390] Amount21
Amount22 [548] Amount20
Amount22 [435] Amount13
Amount22 [2070] Amount14
Amount22 [6773] Amount19

Amount15 [22448] Amount16

Amount16 [1583] Amount23
Amount23 [1583] Amount24

Amount16 [20865] Amount25

Amount25 [938] Amount26
Amount25 [2063] Amount12
Amount25 [3128] Amount38
Amount25 [1200] Amount27
Amount25 [7500] Amount40
Amount25 [225] Amount39
Amount25 [5250] Amount28
Amount25 [13125] Amount41
Amount25 [2250] Amount30
Amount25 [5625] Amount34
Amount25 [713] Amount36

Amount41 [5475] Amount31
Amount41 [2250] Amount32
Amount41 [1350] Amount33
Amount41 [3863] Amount35
Amount41 [188] Amount37
```

**Comment by waldyrious** [comment]
I think this may be the same problem as the one reported in #28. If so, I believe it might make sense to close this issue as a duplicate and centralize the discussion there.

**Comment by nowthis** [comment]
Good news - the recent layout improvements (mentioned on https://sankeymatic.com/news/ ) have made this diagram come out much better.

@totti4ever Here's the layout when using your inputs in a fresh load of the page with the following settings tweaks:
* Diagram Width = 1200
* Default node color = one color
* Labels: Size = 12, Placement = Outside, Suffix = €

![sankeymatic_20221113_141126_1200x600](https://user-images.githubusercontent.com/5286645/201540133-d9ee1102-35ce-4311-8165-38ff6bc6327a.png)

There can still be some odd crossings depending on how you set the Node Height and Node Spacing sliders, but most of the combinations of those two controls produce this arrangement.

Closing this issue.

Thanks for the sample data, it was a good test set to use while I was working on the algorithm.
