### ISSUE TITLE
Broken? "Place all flow origins at the left edge"

### ISSUE THREAD

**Issue by parallelprovideo** [nowthis/sankeymatic#78]
Toggling this on and off does not make any changes to the diagram.

I can reverse the diagram and then see changes when toggling it.

I can also see the final result I am looking for in the reverse view with "Place all flow endpoints at the right edge" toggled, so I do believe the final result is possible.

Something appears to not be working?

Thanks for your help!

**Comment by nowthis** [comment]
I've tried on the site and it's working for me - here's an [example diagram](https://sankeymatic.com/build/?i=IYAg2gTAuiBGBQtwEYYDNEpgY3t80IAJvAKZYi4DOAlgF7kDuIAbAAxvwggAWIALB3gBbYACcA5jQB2IADYhkELiDGLl3AC6KAHCqQROsCZQD2c02oDEaW3ZWaxwaVQAO40tO0A5eNNNETOoqfACsnNxuwNgyJgDMGnCWgWoRIJo8pMLk%2DtKkKtjmliBWAOzlFSqm7jGaAJ6K8GgWzNgArmIAbsCaHeRsAHShKjKZYjSaaGKmwiC5%2BdyFFtYAnGvrVTUTDYP8w3LAdaZt2smkasAnMz00uNwAVm1UmjRoR%2BNSLiC%2BD08vb54iFRvioxKROucqKQJE5XHwfiAeppojwZIVhK45KRNKRnqY5qQPM94AdYKQ5MClsUrBxaWlUYEQdxURIeHIaKztINSsNuGhTF40NFyFRnFQALRQ8YYbjsvJRGLSEyDRJgg4vCG0BiKITcUQSaSvBrIISk8nSYDZRGuVyEsTAgCaKi15GQem4jFIHJ42kEnDNcm6cja5GANrtjpUaDacjkrjBMVoApATu4rlMtBeyeAaBxYhUnu9vtNwDJcYzExo2auwHZBpAaSo2EyVsumlMUZo9u0ZP5YP0YOAAGt0zJtMMgyGQH3RNoAOQAGgGc5U8dIaBoAA8QHOV5E2rYtzuVxksqRTLYodpQCt9A2CvfuER79lkSBsl4qy5nEPSHVZ7cKYqOyzw0MIsC1s42C4imQA) for which both the 'left edge' and 'right edge' checkboxes have an effect.

Would you mind sharing your diagram's data in some way, or perhaps a screenshot (without labels if you prefer)?

**Comment by parallelprovideo** [comment]
Hi Steve,

Thanks for taking the time to help me out!

https://sankeymatic.com/build/
<https://sankeymatic.com/build/?i=MIQwzgFgZgNg9gdwAQG0AsBGAHABgLpKiRJwB2SAEiKQCYBQR08yKArDhwQMogBuAlqQDmYBuCaJUANg74kXAA4BTWoKF0AIv15KwAFwC2KvWGkBOXAUaxEdOwFEQAJ1JrTKDHOvM6ASVJ6Sk66eqieBI4ubnSRrsLurFbiNghikABGIADGANaoiUix0UXxqADsXsk%2BAApwgiblciUidADicDouRgFhWADMSZApbVwAKr0DSO2dpN16dgv%2BWXBGYThSZoMSqdXOIDAwSjBIABQAQk7UNCoAlGsbBEsrSnRcEM5KEHAw105IADJwainC5XW73TZIXaXA5HEGXWi3PykZarFAAJikWCkW2G0P2h2O5wR11IdwxWJxSCeRjoAHUQEJdPCwWTUJjsQR8bCiaDEWTkailKhMGUyriansead%2Ds5%2BGAwCByaLxdSUc96YzmSdZU55YrlRgxVypYSZXKFUqFox5Hw3NIcOi5FodPo5qIKL4uABBGV3AByAFcztQ8igzDICC6Qu7XnbSh4sOwCBQ4IGwMKeAJ4nRU%2BnM%2DGRL1k0gAGIUH1%2BpB0pT7PQQMD8AwKQ5x7NFjHheSCHJqMuB2iiLg9vulgc0dzorvVYJgLJ6hR6fhkW3toeF9x9Tjd0i94T9wevEf7seD1BbppGJxMlEAT1X0Sz9pQfUsZd8ACV7HRS5%2D7Oe3w%2DDQuGqNtnzQbdh13UdxyHY8hAPCcRW3UZLh0Y4nxzTCOzfX8vx%2DP9UEAj8QJBO4AEVAxCS5rjAhN%2BjkKC9wQ08JyPaCT1goitySP5sPXNdUDMEs8wzB8c1EgtBPDEty0rc4KKo%2DQaJeOxFBUGg%2Bw8HAzDkUs4Dgeh9MMtZdIIVonDgLIgn4XRXmUVR9w8LsKFrGB61zNz6zCLtWlvAx7I0rSMHYORRLUXM00bJyQu3D9jECxyEI8CoCFQ6gwAUOAnD0EAlzIOh0tITLsty%2DLyBSuR%2DDAQMEWsxLNJit8ipKnK8uXUhCoRVqyo63o5FacAGq0qc5BarK2vKrqMom3qV07OQAFkQHqFRqHq9SkvZEtgHePVcvSQ4kA0Mh2rIURdrlA6jpO0gzuK7axv4esXk2xrkvRN9Lv2kBDuFW77ouvbnt%2Bm7TvKycvuBvRb2Gpz0TMwgVgMAd%2BCye6GGR1H0fK9lEeAI5jmqL5SFehz3vPJ0rGh0HhVafgoBMBgab%2BqYGYaF8qahU04Xpxmh3JrTXy8LHXBxjrMYMFGxfugCqoCIJSfmN6tNYCCUy8iBPLrCB8nVqFZ3nfhFw6gWgqcrExrQo5pvQ6RcJAAx%2BBge9UON0Q7AALhpYUAGJ0U%2Bs4A4APmDuhPZV%2DdfeACocD6MwAB4E%2DD%2DikF90tS29UKk%2DD7kzWJVk7l9jAsg2KQlFD3OeaJXV9SVNOS7Livg4ASBbuhGwAL2FZAMHRdg6CQJBdc8Dg6AMZwhEEJBjj7wekD%2BOeh9CbB5%2DSJAnTodIEOWeA%2Dl9qBD6P%2Be9G6hQPh6f06FIQye6QMx591tApHnzLsj7Ue1%2By34kAwE%2BICUKsdI89d7ZTTlgCBkD55wHPlkZ694%2D4pCQFkWqvA8q1WFDgAAdH%2DIeggAH7SgJZAwSAwBpicPVIeoD95mFoXQ6BsD4FIGwWgVgdAYAgFvGmUI38ghIBAIGPQKx2pZHngAK3TEuKAXC9RTwelfIeEj9AM1vBpUwCiF5KE6BmIQlwFC6w0XlXKWQICCFRC2JQgR9BwCQKTD4%2Bh2G%2DSOKYahadZCyEfvwa4SANGmKEBAGA%2DB%2DGhGwVgeeUAyB6CgNkYUipioAFoMx6igPPQJpM35wP3Ng9E89ggcKXK6fg3df5jyHhPIQrhpElJwI49IRw7qrBAAoZQzhTAAE1X5FOFEvJACAlBBIgKECCNSOF1JgGgmAVF%2BHNNrE4dp4TAwHAUMEOBjYVwdKHllRsuMxm2CHn0gZQyx6jKOFs56fUBFCP2EE8g8TcGkJMYA4Uly4DhP4HM0IdSInBDXsEEAOQsr1CQGgOgEypnfInqEAA5AAGiwVC%2BeyylBQH4AADyQFCgAJAioeNVD5ooxQil6Rg4CHwzKEEA9815ID6CA5h88aD0qMLlJAcxTahiUP5ERPjUnyiXAYTIHCUTMjaUAA>

Above is my exact Sankey (I shortened the link but it should open to the
proper full link)

I also entered my data into the Sankey link you sent and the toggle again
didn't change anything.

So is there something I have done wrong in my formatting of the data?

Thanks,

*Branden Murphy*
Video Producer, Owner

Parallel Productions Inc.
parallelproductions.ca <https://www.parallelproductions.ca/>
(705) 890-1772

**Comment by nowthis** [comment]
Ok, I see the issue now. It seems to be a problem with the initial layout phase, not with the checkbox itself.

If the layout algorithm would put the items in the top left of your diagram one more stage to the right instead, then the checkbox would have something to affect; as it is right now, everything starts out already in the first stage and so nothing changes.

I will look into this, but I can't promise a particular timeline.

**Comment by nowthis** [comment]
Commit 088a339 ought to handle this issue, and it is now posted on the site.

Clicking the public-diagram link posted above will now render differently, and checking the "Place all flow origins at the left edge" checkbox does now have an effect.

The commit message for the above change describes a bit more about the change, but the easiest thing to see is a basic comparison, using these inputs:
```
i [1] j
a [2] b
b [1] f
b [1] c
c [2] d
e [1] c
g [1] h
h [1] d
a [1] i
``` 
Before the change, the output looked like this:
![example-before](https://github.com/nowthis/sankeymatic/assets/5286645/037a9db7-9c00-4a54-95e1-5f1b666187c2)
The flow `g->h` ought to be mirroring the placement of the flow `i->j`, but it's all the way to the left instead.
Put another way, there's no real reason for `h->d` to be crossing two stages.

After the change, the same inputs produce the right symmetrical outcome:
![example-after](https://github.com/nowthis/sankeymatic/assets/5286645/33b13219-a929-4c47-b8b7-f471b550533e)

**Comment by parallelprovideo** [comment]
Amazing!

Thank you so much for changing this - I've really been enjoying using the
site since I found it a few months ago!

All the best,

*Branden Murphy*
Video Producer, Owner

Parallel Productions Inc.
parallelproductions.ca <https://www.parallelproductions.ca/>
(705) 890-1772
