### ISSUE TITLE
Citation Information Request

### ISSUE THREAD

**Issue by cdixo** [nowthis/sankeymatic#81]
Hi Steve and team,

Firstly, let me thank you for such a wonderful program.  It works so well, has so much functionality that can be adjusted, and yet is very elegant.  Really awesome job.  That in mind, I would like to cite the program/you/the team/a publication in my upcoming publication as I use your tool in part to make a figure panel.  How should I cite the tool?  Can you make a 'Citation Information' tab on your website or place the information somewhere accessible?  You deserve to be recognized for your hard work!

Best,

Cullen

**Comment by nowthis** [comment]
Hi @cdixo and thank you very much for the kind words.

It looks like there is a nice existing convention for setting up a 'CITATION' file; see https://citation-file-format.github.io/about/
I will assign this to myself and work on it soon.

(I will also attempt to answer the question here first – you won't have to wait until the code change is complete. Hopefully this weekend.)

Thanks again.

**Comment by cdixo** [comment]
Sounds great!  I'll be sure to use it once I have the citation.
